
import { Role, TeamConfig, Player } from './types';

export const TEAMS: TeamConfig[] = [
  { id: 'CSK', name: 'Chennai Super Kings', shortName: 'CSK', color: '#FFFF35', secondaryColor: '#005CA8', logo: 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/CSK/logos/Logo-Round/CSKroundbig.png' },
  { id: 'MI', name: 'Mumbai Indians', shortName: 'MI', color: '#004BA0', secondaryColor: '#D1AB3E', logo: 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/MI/logos/Logo-Round/MIroundbig.png' },
  { id: 'RCB', name: 'Royal Challengers Bengaluru', shortName: 'RCB', color: '#EC1C24', secondaryColor: '#2B2A29', logo: 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/RCB/logos/Logo-Round/RCBroundbig.png' },
  { id: 'KKR', name: 'Kolkata Knight Riders', shortName: 'KKR', color: '#3A225D', secondaryColor: '#F2D06B', logo: 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/KKR/logos/Logo-Round/KKRroundbig.png' },
  { id: 'DC', name: 'Delhi Capitals', shortName: 'DC', color: '#00008B', secondaryColor: '#EF1B23', logo: 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/DC/logos/Logo-Round/DCroundbig.png' },
  { id: 'PBKS', name: 'Punjab Kings', shortName: 'PBKS', color: '#ED1B24', secondaryColor: '#D1D3D4', logo: 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/PBKS/logos/Logo-Round/PBKSroundbig.png' },
  { id: 'RR', name: 'Rajasthan Royals', shortName: 'RR', color: '#EA1A85', secondaryColor: '#004B8C', logo: 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/RR/logos/Logo-Round/RRroundbig.png' },
  { id: 'SRH', name: 'Sunrisers Hyderabad', shortName: 'SRH', color: '#F26522', secondaryColor: '#231F20', logo: 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/SRH/logos/Logo-Round/SRHroundbig.png' },
  { id: 'GT', name: 'Gujarat Titans', shortName: 'GT', color: '#1B2133', secondaryColor: '#B8975D', logo: 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/GT/logos/Logo-Round/GTroundbig.png' },
  { id: 'LSG', name: 'Lucknow Super Giants', shortName: 'LSG', color: '#0057E2', secondaryColor: '#FF4D4D', logo: 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/LSG/logos/Logo-Round/LSGroundbig.png' },
];

export const INITIAL_PLAYER_POOL: Player[] = [
  // BATTERS (BA1-BA2)
  { id: 1, name: "Rohit Sharma", country: "India", role: Role.BAT, basePrice: 200, set: "BA1", overseas: false },
  { id: 2, name: "Virat Kohli", country: "India", role: Role.BAT, basePrice: 200, set: "BA1", overseas: false },
  { id: 3, name: "Travis Head", country: "Australia", role: Role.BAT, basePrice: 200, set: "BA1", overseas: true },
  { id: 4, name: "Shubman Gill", country: "India", role: Role.BAT, basePrice: 200, set: "BA1", overseas: false },
  { id: 5, name: "Devon Conway", country: "New Zealand", role: Role.BAT, basePrice: 200, set: "BA1", overseas: true },
  { id: 6, name: "David Warner", country: "Australia", role: Role.BAT, basePrice: 200, set: "BA1", overseas: true },
  { id: 7, name: "Yashasvi Jaiswal", country: "India", role: Role.BAT, basePrice: 150, set: "BA2", overseas: false },
  { id: 8, name: "Ruturaj Gaikwad", country: "India", role: Role.BAT, basePrice: 150, set: "BA2", overseas: false },
  { id: 9, name: "Suryakumar Yadav", country: "India", role: Role.BAT, basePrice: 200, set: "BA1", overseas: false },
  { id: 10, name: "Kane Williamson", country: "New Zealand", role: Role.BAT, basePrice: 200, set: "BA1", overseas: true },
  { id: 51, name: "Faf du Plessis", country: "South Africa", role: Role.BAT, basePrice: 200, set: "BA1", overseas: true },
  { id: 52, name: "Steve Smith", country: "Australia", role: Role.BAT, basePrice: 200, set: "BA2", overseas: true },
  { id: 53, name: "Harry Brook", country: "England", role: Role.BAT, basePrice: 150, set: "BA2", overseas: true },
  { id: 54, name: "Sai Sudharsan", country: "India", role: Role.BAT, basePrice: 20, set: "BA4", overseas: false },
  { id: 55, name: "Rinku Singh", country: "India", role: Role.BAT, basePrice: 50, set: "BA4", overseas: false },
  
  // ALL ROUNDERS (AR1-AR2)
  { id: 11, name: "Hardik Pandya", country: "India", role: Role.AR, basePrice: 200, set: "AR1", overseas: false },
  { id: 12, name: "Ravindra Jadeja", country: "India", role: Role.AR, basePrice: 200, set: "AR1", overseas: false },
  { id: 13, name: "Rashid Khan", country: "Afghanistan", role: Role.AR, basePrice: 200, set: "AR1", overseas: true },
  { id: 14, name: "Glenn Maxwell", country: "Australia", role: Role.AR, basePrice: 200, set: "AR1", overseas: true },
  { id: 15, name: "Andre Russell", country: "West Indies", role: Role.AR, basePrice: 200, set: "AR1", overseas: true },
  { id: 16, name: "Axar Patel", country: "India", role: Role.AR, basePrice: 150, set: "AR1", overseas: false },
  { id: 17, name: "Mitchell Marsh", country: "Australia", role: Role.AR, basePrice: 150, set: "AR1", overseas: true },
  { id: 18, name: "Cameron Green", country: "Australia", role: Role.AR, basePrice: 200, set: "AR1", overseas: true },
  { id: 19, name: "Ben Stokes", country: "England", role: Role.AR, basePrice: 200, set: "AR1", overseas: true },
  { id: 20, name: "Moeen Ali", country: "England", role: Role.AR, basePrice: 100, set: "AR2", overseas: true },
  { id: 56, name: "Liam Livingstone", country: "England", role: Role.AR, basePrice: 150, set: "AR1", overseas: true },
  { id: 57, name: "Sam Curran", country: "England", role: Role.AR, basePrice: 200, set: "AR1", overseas: true },
  { id: 58, name: "Marcus Stoinis", country: "Australia", role: Role.AR, basePrice: 150, set: "AR1", overseas: true },
  { id: 59, name: "Krunal Pandya", country: "India", role: Role.AR, basePrice: 75, set: "AR2", overseas: false },
  { id: 60, name: "Washington Sundar", country: "India", role: Role.AR, basePrice: 100, set: "AR2", overseas: false },

  // WICKET KEEPERS (WK1-WK2)
  { id: 21, name: "Rishabh Pant", country: "India", role: Role.WK, basePrice: 200, set: "WK1", overseas: false },
  { id: 22, name: "Heinrich Klaasen", country: "South Africa", role: Role.WK, basePrice: 200, set: "WK1", overseas: true },
  { id: 23, name: "Jos Buttler", country: "England", role: Role.WK, basePrice: 200, set: "WK1", overseas: true },
  { id: 24, name: "KL Rahul", country: "India", role: Role.WK, basePrice: 200, set: "WK1", overseas: false },
  { id: 25, name: "Sanju Samson", country: "India", role: Role.WK, basePrice: 200, set: "WK1", overseas: false },
  { id: 26, name: "Ishaan Kishan", country: "India", role: Role.WK, basePrice: 150, set: "WK2", overseas: false },
  { id: 27, name: "Nicholas Pooran", country: "West Indies", role: Role.WK, basePrice: 200, set: "WK1", overseas: true },
  { id: 28, name: "Phil Salt", country: "England", role: Role.WK, basePrice: 100, set: "WK2", overseas: true },
  { id: 29, name: "Quinton de Kock", country: "South Africa", role: Role.WK, basePrice: 150, set: "WK2", overseas: true },
  { id: 30, name: "Jitesh Sharma", country: "India", role: Role.WK, basePrice: 50, set: "WK3", overseas: false },
  { id: 61, name: "Dhruv Jurel", country: "India", role: Role.WK, basePrice: 20, set: "WK4", overseas: false },
  { id: 62, name: "Abhishek Porel", country: "India", role: Role.WK, basePrice: 20, set: "WK4", overseas: false },
  { id: 63, name: "Dinesh Karthik", country: "India", role: Role.WK, basePrice: 50, set: "WK3", overseas: false },
  { id: 64, name: "Matthew Wade", country: "Australia", role: Role.WK, basePrice: 100, set: "WK2", overseas: true },

  // BOWLERS (BO1-BO3)
  { id: 31, name: "Jasprit Bumrah", country: "India", role: Role.BOWL, basePrice: 200, set: "BO1", overseas: false },
  { id: 32, name: "Mitchell Starc", country: "Australia", role: Role.BOWL, basePrice: 200, set: "BO1", overseas: true },
  { id: 33, name: "Mohammed Shami", country: "India", role: Role.BOWL, basePrice: 200, set: "BO1", overseas: false },
  { id: 34, name: "Kagiso Rabada", country: "South Africa", role: Role.BOWL, basePrice: 200, set: "BO1", overseas: true },
  { id: 35, name: "Trent Boult", country: "New Zealand", role: Role.BOWL, basePrice: 200, set: "BO1", overseas: true },
  { id: 36, name: "Kuldeep Yadav", country: "India", role: Role.BOWL, basePrice: 150, set: "BO2", overseas: false },
  { id: 37, name: "Yuzvendra Chahal", country: "India", role: Role.BOWL, basePrice: 100, set: "BO2", overseas: false },
  { id: 38, name: "Adam Zampa", country: "Australia", role: Role.BOWL, basePrice: 100, set: "BO2", overseas: true },
  { id: 39, name: "Sunil Narine", country: "West Indies", role: Role.BOWL, basePrice: 200, set: "BO1", overseas: true },
  { id: 40, name: "Mohammed Siraj", country: "India", role: Role.BOWL, basePrice: 150, set: "BO2", overseas: false },
  { id: 41, name: "Pat Cummins", country: "Australia", role: Role.BOWL, basePrice: 200, set: "BO1", overseas: true },
  { id: 45, name: "Arshdeep Singh", country: "India", role: Role.BOWL, basePrice: 100, set: "BO3", overseas: false },
  { id: 46, name: "Harshal Patel", country: "India", role: Role.BOWL, basePrice: 100, set: "BO3", overseas: false },
  { id: 65, name: "Anrich Nortje", country: "South Africa", role: Role.BOWL, basePrice: 200, set: "BO1", overseas: true },
  { id: 66, name: "Lockie Ferguson", country: "New Zealand", role: Role.BOWL, basePrice: 150, set: "BO2", overseas: true },
  { id: 67, name: "Naveen-ul-Haq", country: "Afghanistan", role: Role.BOWL, basePrice: 50, set: "BO3", overseas: true },
  { id: 68, name: "Ravi Bishnoi", country: "India", role: Role.BOWL, basePrice: 75, set: "BO2", overseas: false },
  { id: 69, name: "Varun Chakaravarthy", country: "India", role: Role.BOWL, basePrice: 100, set: "BO2", overseas: false },
  { id: 70, name: "Khaleel Ahmed", country: "India", role: Role.BOWL, basePrice: 50, set: "BO3", overseas: false },

  // UNCAPPED & ADDITIONAL (UBA, UBO, UAR, UWK)
  { id: 49, name: "Mayank Yadav", country: "India", role: Role.BOWL, basePrice: 20, set: "BO4", overseas: false },
  { id: 71, name: "Sameer Rizvi", country: "India", role: Role.BAT, basePrice: 20, set: "UBA1", overseas: false },
  { id: 72, name: "Ashutosh Sharma", country: "India", role: Role.BAT, basePrice: 20, set: "UBA1", overseas: false },
  { id: 73, name: "Shashank Singh", country: "India", role: Role.BAT, basePrice: 20, set: "UBA1", overseas: false },
  { id: 74, name: "Angkrish Raghuvanshi", country: "India", role: Role.BAT, basePrice: 20, set: "UBA1", overseas: false },
  { id: 75, name: "Suyash Sharma", country: "India", role: Role.BOWL, basePrice: 20, set: "UBO1", overseas: false },
  { id: 76, name: "Vaibhav Arora", country: "India", role: Role.BOWL, basePrice: 20, set: "UBO1", overseas: false },
  { id: 77, name: "Harshit Rana", country: "India", role: Role.BOWL, basePrice: 20, set: "UBO1", overseas: false },
  { id: 78, name: "Nitish Reddy", country: "India", role: Role.AR, basePrice: 20, set: "UAR1", overseas: false },
  { id: 79, name: "Shahrukh Khan", country: "India", role: Role.AR, basePrice: 40, set: "UAR1", overseas: false },
  { id: 80, name: "Rahul Tewatia", country: "India", role: Role.AR, basePrice: 40, set: "UAR1", overseas: false },
  
  // FILLER PLAYERS TO REACH 100
  { id: 81, name: "Jason Roy", country: "England", role: Role.BAT, basePrice: 150, set: "BA3", overseas: true },
  { id: 82, name: "Finn Allen", country: "New Zealand", role: Role.BAT, basePrice: 75, set: "BA3", overseas: true },
  { id: 83, name: "Temba Bavuma", country: "South Africa", role: Role.BAT, basePrice: 100, set: "BA3", overseas: true },
  { id: 84, name: "Ajinkya Rahane", country: "India", role: Role.BAT, basePrice: 50, set: "BA4", overseas: false },
  { id: 85, name: "Manish Pandey", country: "India", role: Role.BAT, basePrice: 50, set: "BA4", overseas: false },
  { id: 86, name: "Wanindu Hasaranga", country: "Sri Lanka", role: Role.AR, basePrice: 150, set: "AR1", overseas: true },
  { id: 87, name: "Maheesh Theekshana", country: "Sri Lanka", role: Role.BOWL, basePrice: 100, set: "BO2", overseas: true },
  { id: 88, name: "Matheesha Pathirana", country: "Sri Lanka", role: Role.BOWL, basePrice: 20, set: "BO4", overseas: true },
  { id: 89, name: "Dilshan Madushanka", country: "Sri Lanka", role: Role.BOWL, basePrice: 50, set: "BO3", overseas: true },
  { id: 90, name: "Josh Hazlewood", country: "Australia", role: Role.BOWL, basePrice: 200, set: "BO1", overseas: true },
  { id: 91, name: "Mustafizur Rahman", country: "Bangladesh", role: Role.BOWL, basePrice: 200, set: "BO2", overseas: true },
  { id: 92, name: "Taskin Ahmed", country: "Bangladesh", role: Role.BOWL, basePrice: 75, set: "BO3", overseas: true },
  { id: 93, name: "Noor Ahmad", country: "Afghanistan", role: Role.BOWL, basePrice: 50, set: "BO3", overseas: true },
  { id: 94, name: "Azmatullah Omarzai", country: "Afghanistan", role: Role.AR, basePrice: 50, set: "AR3", overseas: true },
  { id: 95, name: "Ibrahim Zadran", country: "Afghanistan", role: Role.BAT, basePrice: 50, set: "BA3", overseas: true },
  { id: 96, name: "Rahmanullah Gurbaz", country: "Afghanistan", role: Role.WK, basePrice: 50, set: "WK3", overseas: true },
  { id: 97, name: "Litton Das", country: "Bangladesh", role: Role.WK, basePrice: 50, set: "WK3", overseas: true },
  { id: 98, name: "Shakib Al Hasan", country: "Bangladesh", role: Role.AR, basePrice: 150, set: "AR1", overseas: true },
  { id: 99, name: "Mehidy Hasan Miraz", country: "Bangladesh", role: Role.AR, basePrice: 50, set: "AR3", overseas: true },
  { id: 100, name: "Sikandar Raza", country: "Zimbabwe", role: Role.AR, basePrice: 50, set: "AR3", overseas: true },
];
